apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    receivers:
    - name: "null"
    - name: "alertmananger-bot"
      webhook_configs:
      - send_resolved: true
        http_config: {}
        url: http://alertmanager-bot:8080
    route:
      group_by:
      - alertname
      - namespace
      group_interval: 5m
      group_wait: 40s
      receiver: "alertmananger-bot"
      repeat_interval: 2h
      routes:
      - match:
          alertname: Watchdog
        receiver: "null"
        continue: false
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'namespace', 'host', 'instance']
