apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul
  labels:
    k8s-app: consul
  namespace: consul
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: consul
  endpoints:
  - port: http
    path: /v1/agent/metrics
    params:
      format: [prometheus]
