apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: consul-exporter
  name: consul-exporter
  namespace: consul
spec:
  ports:
  - name: http
    port: 9107
    targetPort: 9107
  selector:
    app.kubernetes.io/name: consul-exporter
