apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: consul-server
    k8s-app: consul
  name: server
  namespace: consul
spec:
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  selector:
    app.kubernetes.io/name: consul-server
