apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-etcd
  namespace: monitoring
  labels:
    k8s-app: kube-etcd
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      k8s-app: kube-etcd
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/etcd-client/ca.crt
      certFile: /etc/prometheus/secrets/etcd-client/healthcheck-client.crt
      keyFile: /etc/prometheus/secrets/etcd-client/healthcheck-client.key
      insecureSkipVerify: true
