apiVersion: v1
kind: Service
metadata:
  name: kube-etcd-metrics
  labels:
    k8s-app: kube-etcd
    jobLabel: kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    component: etcd
  type: ClusterIP
