apiVersion: v1
kind: Service
metadata:
  name: kube-router-metrics
  labels:
    k8s-app: kube-router
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: kube-router
  type: ClusterIP
