apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unbound
  labels:
    k8s-app: unbound
  namespace: network-tools
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
  podMetricsEndpoints:
  - port: metrics
