---
- name: Common settings
  import_playbook: playbooks/common.yml
- name: Apply os tunables
  import_playbook: playbooks/performance-tuning.yml
- name: Extended monitoring
  import_playbook: playbooks/extended-monitoring.yml
