apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: manual
        resources:
          requests:
            storage: 50Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  secrets:
  - etcd-client
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  additionalScrapeConfigs:
    name: prometheus-scrape-configs
    key: prometheus-additional.yaml
  version: v2.15.2
  thanos:
    image: "quay.io/thanos/thanos:v0.10.1"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    objectStorageConfig:
      name: thanos-config
      key: objstore-config
