- name: Configure system.conf 
  template:
    src: "system.conf.j2"
    dest: /etc/systemd/system.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd reload

- name: Configure journald.conf
  template:
    src: "journald.conf.j2"
    dest: /etc/systemd/journald.conf
    mode: 0644
    owner: root
    group: root
  notify: journald reload
