apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
  labels:
    k8s-app: traefik
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
  - port: admin
