apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: thanos-sidecar
  namespace: monitoring
spec:
  jobLabel: thanos-component
  endpoints:
  - interval: 30s
    port: thanos
  selector:
    matchLabels:
      prometheus: k8s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: thanos
  namespace: monitoring
spec:
  jobLabel: thanos-component
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
