apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unbound
  labels:
    k8s-app: unbound
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - network-tools
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
  podMetricsEndpoints:
  - port: metrics
