apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=60
    - retrans=10
  capacity:
    storage: 100Gi
  nfs:
    server: ""
    path: ""
  persistentVolumeReclaimPolicy: "Retain"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: warehouse
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: "postgresql-data-pv"
  storageClassName: ""
