apiVersion: v1
kind: Service
metadata:
  name: metallb-speaker-metrics
  labels:
    k8s-app: metallb
  namespace: metallb-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 7472
      protocol: TCP
      targetPort: 7472
  selector:
    app: metallb
    component: speaker
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-metrics
  labels:
    k8s-app: metallb
  namespace: metallb-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 7472
      protocol: TCP
      targetPort: 7472
  selector:
    app: metallb
    component: controller
  type: ClusterIP
