apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eclipse-mosquitto
  labels:
    k8s-app: eclipse-mosquitto
  namespace: internet-of-things
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: eclipse-mosquitto
  podMetricsEndpoints:
  - port: http
