apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: internet-of-things
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
    spec:
      hostNetwork: true
      containers:
        - name: home-assistant
          image: "homeassistant/home-assistant:0.104.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 180
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /config
            name: config-data
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
      - name: config-data
        persistentVolumeClaim:
            claimName: homeassistant-data-pvc
      dnsConfig:
        options:
        - name: ndots
          value: "1"
