apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-metrics
  labels:
    k8s-app: kube-scheduler
    jobLabel: kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    component: kube-scheduler
  type: ClusterIP
