apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mariadb
  name: mariadb
  namespace: wordpress
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: metrics
    port: 9104
    targetPort: 9104
  selector:
    app.kubernetes.io/name: mariadb
