---
chrony_pkg_state: present
chrony_service_state: started
chrony_service_enabled: yes
chrony_config_server:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
chrony_config_logdir: /var/log/chrony
chrony_timezone: Etc/UTC

chrony_service_name: chrony
chrony_config_location: /etc/chrony/chrony.conf
chrony_config_driftfile: /var/lib/chrony/chrony.drift
chrony_config_keyfile: /etc/chrony/chrony.keys
chrony_tzdata_package: tzdata
