kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner
  namespace: drone
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
subjects:
- kind: ServiceAccount
  name: drone-runner
  namespace: drone
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io

