apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.XY.ZZ
      peer-asn: 64511
      my-asn: 64511
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.XX.0/24
