apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: memcached
  name: memcached
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: 11211
  - name: http
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/name: memcached
