apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: snmp-exporter
  name: snmp-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9116
    targetPort: 9116
  selector:
    app.kubernetes.io/name: snmp-exporter
